name: tic_tac_toe
description: "Play Tic-Tac-Toe"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.17.0 <=3.5.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  google_fonts: ^4.0.4
  fluttertoast: ^8.2.8
  url_launcher: ^6.3.0
  provider: ^6.1.2
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/anims/

