// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBzKAh2V5KsDPBEDpm3pmf0tGm4XgD2IA',
    appId: '1:209218899095:web:7bda1db457d45f4c682dd2',
    messagingSenderId: '209218899095',
    projectId: 'tic-tac-toe-8bca9',
    authDomain: 'tic-tac-toe-8bca9.firebaseapp.com',
    storageBucket: 'tic-tac-toe-8bca9.appspot.com',
    measurementId: 'G-2D1Y6MW768',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0BsuOFQU04j6GlemFZx25Rvk07xHLoj4',
    appId: '1:209218899095:android:1bdbe4aafda63221682dd2',
    messagingSenderId: '209218899095',
    projectId: 'tic-tac-toe-8bca9',
    storageBucket: 'tic-tac-toe-8bca9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG-1aDm_5W1eBCydYEStkDZWCf18vYePk',
    appId: '1:209218899095:ios:1dc80a0ea2749481682dd2',
    messagingSenderId: '209218899095',
    projectId: 'tic-tac-toe-8bca9',
    storageBucket: 'tic-tac-toe-8bca9.appspot.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG-1aDm_5W1eBCydYEStkDZWCf18vYePk',
    appId: '1:209218899095:ios:1dc80a0ea2749481682dd2',
    messagingSenderId: '209218899095',
    projectId: 'tic-tac-toe-8bca9',
    storageBucket: 'tic-tac-toe-8bca9.appspot.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBzKAh2V5KsDPBEDpm3pmf0tGm4XgD2IA',
    appId: '1:209218899095:web:5dbba0ac3fce678c682dd2',
    messagingSenderId: '209218899095',
    projectId: 'tic-tac-toe-8bca9',
    authDomain: 'tic-tac-toe-8bca9.firebaseapp.com',
    storageBucket: 'tic-tac-toe-8bca9.appspot.com',
    measurementId: 'G-T77ZF93QN5',
  );
}
